# Generated by Django 4.1 on 2022-08-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loggeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='users',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
