# Generated by Django 4.0.5 on 2022-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
