# Generated by Django 4.0.5 on 2022-07-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toys',
        ),
    ]
