# Generated by Django 4.1 on 2022-08-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_gamesinf_alter_contact_message_gamevote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesinf',
            name='game_name',
            field=models.CharField(default='game', max_length=20),
        ),
    ]
