# Generated by Django 4.1 on 2022-08-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_gamesinf_game_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='game', max_length=20)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gamevote',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamevotes', to='pages.gamesinfo'),
        ),
        migrations.DeleteModel(
            name='GamesInf',
        ),
    ]
