# Generated by Django 4.1 on 2022-08-28 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_gamesinfo_alter_gamevote_game_type_delete_gamesinf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='game', max_length=20, verbose_name='name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
