# Generated by Django 4.1 on 2022-08-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_gamestype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamesType',
        ),
    ]
