# Generated by Django 4.1 on 2022-08-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_delete_gamestype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamevote',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gamevote',
            name='user',
        ),
        migrations.DeleteModel(
            name='GamesInfo',
        ),
        migrations.DeleteModel(
            name='GameVote',
        ),
    ]
