# Generated by Django 4.0.5 on 2022-07-20 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagram_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_size', models.SmallIntegerField(default=3)),
                ('score', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('ranked', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anagramPlayer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
