# Generated by Django 4.0.5 on 2022-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagram_score',
            options={'ordering': ['-point']},
        ),
        migrations.RemoveField(
            model_name='anagram_score',
            name='ranked',
        ),
        migrations.AddField(
            model_name='anagram_score',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
        ),
    ]
