# Generated by Django 4.0.5 on 2022-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram_game', '0003_alter_anagram_score_word_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagram_score',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
