# Generated by Django 4.0.5 on 2022-08-09 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagram_game', '0004_alter_anagram_score_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagram_score',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anagramPlayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
