# Generated by Django 4.1 on 2022-08-20 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagram_game', '0007_alter_anagram_score_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Anagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[(None, '--Please choose--'), ('anagrame', 'Anagrame hunt')], max_length=10)),
                ('comment', models.TextField(max_length=300)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_anagrame', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
