# Generated by Django 4.1 on 2022-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram_game', '0008_comment_anagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_anagram',
            name='game_type',
            field=models.CharField(choices=[(None, '--Please choose--'), ('anagrame', 'AnagrameHunt')], max_length=10),
        ),
    ]
