# Generated by Django 4.0.5 on 2022-07-25 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math_score',
            options={'ordering': ['-point']},
        ),
        migrations.AlterField(
            model_name='math_score',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
