# Generated by Django 4.0.5 on 2022-07-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_game', '0002_alter_math_score_options_alter_math_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math_score',
            name='ranked',
        ),
    ]
