# Generated by Django 4.0.5 on 2022-07-28 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_game', '0003_remove_math_score_ranked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=50)),
                ('max_range', models.SmallIntegerField(default=2)),
                ('score', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additionPlayer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-point'],
            },
        ),
    ]
