# Generated by Django 4.0.5 on 2022-07-29 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_game', '0005_subtraction_score_multiplication_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition_score',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additionPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='division_score',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisionScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multiplication_score',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multiplicationScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtraction_score',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtractionScore', to=settings.AUTH_USER_MODEL),
        ),
    ]
