# Generated by Django 4.0.5 on 2022-08-09 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_game', '0006_alter_addition_score_user_alter_division_score_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math_score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
